#!/bin/bash
# Bash Profile

# LS Colors
export CLICOLOR=1
export LSCOLORS=gxBxhxDxfxhxhxhxhxcxcx

# Set architecture flags
export ARCHFLAGS="-arch x86_64"

# Ensure user-installed binaries take precedence
export PATH=${HOME}/.brew/bin:${PATH}

# Brew git access token
export HOMEBREW_GITHUB_API_TOKEN="GIT_TOKEN_HERE"

# The fuck
eval "$(thefuck --alias)"

# Load .bashrc if it exists
test -f ~/.bashrc && source ~/.bashrc
